version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install -y cmake3
      - cmake3 --version
  build:
    commands:
      - echo Entered the build phase...
      - mkdir build && cd build
      - cmake3 .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=out
      - make
      - make aws-lambda-package-s3Read
  post_build:
    commands:
      - echo Publishing code at `date`
      - aws lambda update-function-code --function-name s3Read --zip-file fileb://s3Read.zip
